---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_license: accept
verifier:
  name: inspec
platforms:
  - name: ubuntu-16.04
    driver_config:
      run_command: /bin/systemd
      privileged: true

  - name: ubuntu-18.04
    driver_config:
      run_command: /bin/systemd
      privileged: true
      provision_command:
        - apt-get install -y net-tools gnupg 
     
suites:
  - name: default
    run_list:
      - recipe[monit::default]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      monit:
        install_method: source